export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_SEARCHED_SUCCESS = 'FETCH_SEARCHED_SUCCESS';
export const FETCH_SEARCHED_FAILURE = 'FETCH_SEARCHED_FAILURE';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DECREASE_PRODUCT = 'DECREASE_PRODUCT';
